### ISSUE TITLE
ablation study on reparam structures of DW conv

### ISSUE THREAD

**Issue by ChengpengChen** [THU-MIG/RepViT#1]
Hi, 
Have you evaluated the reparam structures of the 3x3dw conv?
We found that as a reparamed branch, 1x1dw conv contributes little or even worse gains to 3x3dw conv? How about its performance in RepViT?
refer to our [work](https://github.com/ChengpengChen/RepGhost)

**Comment by jameslahm** [comment]
Thanks. We evaluated the reparam structures of the 3x3dw conv in other variants of RepViT (not M1/M2/M3) before. And we found the 1x1 dw conv can bring an approximate 0.05% accuracy improvement.
