### ISSUE TITLE
about semantic segmentation

### ISSUE THREAD

**Issue by zhangh0920** [THU-MIG/RepViT#10]
I wonder whether the model uses the re-parameter technique when processing semantic segmentation in the testing stage. Thanks a lot.

**Comment by jameslahm** [comment]
Thanks. In the testing stage, the re-parameter structure will be fused like https://github.com/THU-MIG/RepViT/blob/8ef1a71e299fc02ea5eaf201039f310313a66b96/segmentation/repvit.py#L105-L123.

**Comment by zhangh0920** [comment]
Thanks for your apply. But I only see the re-parameter structure used in the classification task but I don't figure out in the segmentation task whether re-parameter structure is used.

**Comment by jameslahm** [comment]
In the segmentation task, re-parameter structure is also used like https://github.com/THU-MIG/RepViT/blob/8ef1a71e299fc02ea5eaf201039f310313a66b96/segmentation/repvit.py#L94-L123

**Comment by zhangh0920** [comment]
I got it! Thanks a lot.
