### ISSUE TITLE
train my own dataset

### ISSUE THREAD

**Issue by Jubbuuliiing** [THU-MIG/RepViT#12]
I want to train my own dataset, how can I modify my class-names?

**Comment by jameslahm** [comment]
Thanks. If you arrange your dataset like ImageNet, you can just set --data-path to your own dataset.
```
/path/to/imagenet-1k/
  train/
    class1/
      img1.jpeg
    class2/
      img2.jpeg
  val/
    class1/
      img3.jpeg
    class2/
      img4.jpeg
```
