### ISSUE TITLE
About Latency Measurement

### ISSUE THREAD

**Issue by Jonydom** [THU-MIG/RepViT#13]
Your work is comprehensive, and I am very interested in the performance testing of RepViT inference speed. Could you please let me know what preparations are needed to reproduce the results locally?

**Comment by jameslahm** [comment]
Thanks. Here are the steps to measure the latency:
1. Export the model to Core ML model
```
python export_coreml.py --model repvit_m1 --ckpt pretrain/repvit_m1_distill_300.pth
```
2. Measure its latency using the [XCode performance tool](https://developer.apple.com/videos/play/wwdc2022/10027/) like https://github.com/THU-MIG/RepViT#latency-measurement

**Comment by Jonydom** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Jonydom** [comment]
> Thanks. Here are the steps to measure the latency:
> 
> 1. Export the model to Core ML model
> 
> ```
> python export_coreml.py --model repvit_m1 --ckpt pretrain/repvit_m1_distill_300.pth
> ```
> 
> 2. Measure its latency using the [XCode performance tool](https://developer.apple.com/videos/play/wwdc2022/10027/) like https://github.com/THU-MIG/RepViT#latency-measurement

Thanks for your reply. Is there an open-source website or software available for XCode performance tool? Could you please provide a detailed introduction on how to use the XCode performance tool? Thank you very much for your information.

**Comment by jameslahm** [comment]
Thanks. You could refer to this video https://developer.apple.com/videos/play/wwdc2022/10027/ (starting at around the 4-minute mark).

**Comment by Jonydom** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
