### ISSUE TITLE
What is the training parameters of RepViT while using Timm repository？

### ISSUE THREAD

**Issue by Anleeno-Xu** [THU-MIG/RepViT#15]

**Comment by jameslahm** [comment]
Thanks. You could refer to https://github.com/THU-MIG/RepViT/blob/8ef1a71e299fc02ea5eaf201039f310313a66b96/main.py#L30-L186 for all training parameters.

**Comment by Anleeno-Xu** [comment]
Thanks! How long does it take to train the model using 8 RTX3090 GPUs? Do I need to modify the training parameters using 4 GPUs?

**Comment by Anleeno-Xu** [comment]
@jameslahm Thanks! How long does it take to train the model using 8 RTX3090 GPUs? Do I need to modify the training parameters using 4 GPUs?

**Comment by jameslahm** [comment]
> How long does it take to train the model using 8 RTX3090 GPUs?

It costs ~34 hours to train RepViT-M1 using 8 RTX3090 GPUs. 
> Do I need to modify the training parameters using 4 GPUs?

No need.
