### ISSUE TITLE
A few files are missing

### ISSUE THREAD

**Issue by flied-fish** [THU-MIG/RepViT#2]
Hello author, it seems that the files in the mmseg, mmdet, and mmcv folders are missing here. Could you please upload them

**Comment by jameslahm** [comment]
Hi, you can install the corresponding packages. For example
```
# For mmcv folders
pip install mmcv-full
# For mmseg folders
pip install mmsegmentation
# For mmdet folders
pip install mmdet 
```

**Comment by flied-fish** [comment]
okay, thank you very much
