### ISSUE TITLE
Congrats! Question about the results without distillation

### ISSUE THREAD

**Issue by ma-xu** [THU-MIG/RepViT#20]
Dear authors, 

Congrats on your great work!

I have a questions about the results without distillation. If any results without distillation for the RepViT models are provided?

Thanks in advance.

Best,
Xu

**Comment by jameslahm** [comment]
Thanks for your interest. We will release the results and weights without distillation.

**Comment by jameslahm** [comment]
Thanks for your interest. Please refer to our [latest version](https://arxiv.org/pdf/2307.09283.pdf) for the results without distillation.
![image](https://github.com/THU-MIG/RepViT/assets/43805318/2c553a6b-a543-4329-a46b-2ee7dd011f71)
