### ISSUE TITLE
need clip pretrain 👅👅👅👅

### ISSUE THREAD

**Issue by ZHEQIUSHUI** [THU-MIG/RepViT#26]

**Comment by jameslahm** [comment]
Thanks for your interest. Do you mean the mask decoder supporting text prompt?

**Comment by ZHEQIUSHUI** [comment]
just like [openai/CLIP](https://github.com/openai/CLIP) 😘

**Comment by jameslahm** [comment]
Thanks. This project is not so relevant to CLIP.
