### ISSUE TITLE
[project] grounded-repvit-sam demo support

### ISSUE THREAD

**Issue by rentainhe** [THU-MIG/RepViT#29]
Hello! Thanks a lot for your great work! We've already supported [grounded-repvit-sam demo](https://github.com/IDEA-Research/Grounded-Segment-Anything/blob/main/EfficientSAM/grounded_repvit_sam.py) in [Grounded-Segment-Anything](https://github.com/IDEA-Research/Grounded-Segment-Anything) !

**Comment by jameslahm** [comment]
Thank you! [Grounded-Segment-Anything](https://github.com/IDEA-Research/Grounded-Segment-Anything) is awesome!
