### ISSUE TITLE
Model classifier weights for  CIFAR100

### ISSUE THREAD

**Issue by moliqingwa** [THU-MIG/RepViT#3]
Hi, will you release the trained classifier weights for all other datasets instead of IMNET ?
I checked  the released repvit_m3 model weights it seems the classifier is for 1000 classes.
Thanks

**Comment by jameslahm** [comment]
Hi, thanks, we have not trained repvit on CIFAR100 yet. I suggest that you could also use the weights pretrained on IMNET to finetune repvit on CIFAR100 as well. And I am sorry that I don't have bandwidth for training repvit on CIFAR100 at the moment.

**Comment by moliqingwa** [comment]
Got it, thanks
