### ISSUE TITLE
您好，请问如何将蒸馏模式改成直接训练模式？

### ISSUE THREAD

**Issue by Castrol68** [THU-MIG/RepViT#37]
您好，使用readme里面的训练命令会默认使用蒸馏模式（加载了教师模型），请问如何修改才能使用直接训练模式（不使用教师模型）？

**Comment by jameslahm** [comment]
Thanks for your interest. You could pass '--distillation-type none' as the command line arguments to disable the distillation, like below
```
python -m torch.distributed.launch --nproc_per_node=8 --master_port 12346 --use_env main.py --model repvit_m0_9 --data-path ~/imagenet --dist-eval --distillation-type none
```
