### ISSUE TITLE
Is the GPU memory usage of RepViT-M1.1 similar to that of ResNet50?

### ISSUE THREAD

**Issue by AlphaPlusTT** [THU-MIG/RepViT#41]
I replaced the original model's backbone ResNet50 with RepViT-M1.1. However, during training, I noticed that the GPU memory usage remained almost the same. Is this normal?

**Comment by jameslahm** [comment]
Hi, I just compared RepViT-M1.1 with ResNet50 in terms of GPU memory during training and inference. Here are the results:
| | RepViT-M1.1 | ResNet50|
|:-:|:-:|:-:|
| Training (bs=256) | 13469MiB | 14617MiB |
| Inference (bs=1024) | 8763MiB| 14333MiB |

In my environment, the GPU memory of RepViT-M1.1 is similar to that of ResNet50 during training but much smaller during inference.
