### ISSUE TITLE
关于用于提取图像特征编码器

### ISSUE THREAD

**Issue by chaoying0115** [THU-MIG/RepViT#42]
您好，非常感谢您们团队的出色工作。我打算将此作为单目深度估计提取图像特征的编码器，文件中有很多版本的repvit的py文件，请问我应该选择哪个呢？

**Comment by jameslahm** [comment]
感谢您的关注~ 您好，文件中不同版本的模型对应不同的计算复杂度和精度。我们建议您根据您的目标复杂度选取合适大小的模型，或者选取跟您基线模型复杂度对标的模型版本。
