### ISSUE TITLE
About pretrain weights

### ISSUE THREAD

**Issue by 6lixueting** [THU-MIG/RepViT#47]
I used repvit_m1_5 as the backbone network and Retinanet head as the detection head to train on the target detection data set, but I did not find the pre-training weights in the code (checkpoint='pretrain/repvit_m1_5_distill_300e.pth'). I used the weights marked in red in the figure below as pre-training weights. but the weight values ​​do not match, so I would like to ask where to download the corresponding weights（pretrain/repvit_m1_5_distill_300e.pth）?
![Uploading 图片1.png…]()

**Comment by jameslahm** [comment]
Thanks for your interest. The image you uploaded is invisible. Would you mind updating the figure?

**Comment by 6lixueting** [comment]
Sorry, the picture I uploaded cannot be displayed normally. The weight I used is Ckpt (M1.5) in RepViT-M1.5 under the Models module in this link.https://github.com/THU-MIG/RepViT/tree/main/detection
