### ISSUE TITLE
What is the torch version suitable for this project?

### ISSUE THREAD

**Issue by ZS-YANG** [THU-MIG/RepViT#5]
thanks for this work. I would like to know what torch version is suitable for this project. 😆

**Comment by jameslahm** [comment]
Thanks, we tested torch==2.0.1 locally. And I think torch versions >= 1.8.0 are fine.

**Comment by ZS-YANG** [comment]
thanks for replay, i have another questions . Firstly, will u provide the code for single gpu training? 
secondly，can the repvit model be successfully deployed through openvino or tensorrt? 😆

**Comment by jameslahm** [comment]
Hi, thanks for the questions. 😊
> Firstly, will u provide the code for single gpu training?

Single gpu training can be enabled by setting the nproc_per_node to 1. For example, 
```bash
python -m torch.distributed.launch --nproc_per_node=1 --master_port 12346 --use_env main.py --model repvit_m1 --data-path ~/imagenet --dist-eval
```

> secondly，can the repvit model be successfully deployed through openvino or tensorrt?

Sure, here is a minimal example to export the model to tensorrt by [Torch-TensorRT](https://github.com/pytorch/TensorRT).
```python
import torch_tensorrt
import utils
torch.autograd.set_grad_enabled(False)

from timm import create_model
import model

model = create_model('repvit_m1')
utils.replace_batchnorm(model)
model = model.to("cuda").eval()

trt_model = torch_tensorrt.compile(model, inputs= [torch_tensorrt.Input((2048, 3, 224, 224))]) 
torch.jit.save(trt_model, "repvit_m1.ts")
```

**Comment by jameslahm** [comment]
Hi, this problem is related to the torch version. You can modify `--local-rank` to `--local_rank` in this line and try again. https://github.com/THU-MIG/RepViT/blob/2d85a4c5b709a99fc81ffe4384333e244fda4ab5/detection/test.py#L95

**Comment by ZS-YANG** [comment]
Thanks， the torch  I tried is 1.12.1. 
I think I should get the code to work firstly，so i will test torch==2.0，thanks.
