### ISSUE TITLE
typeError: repvit_m0_9() got an unexpected keyword argument 'pretrained_cfg'

### ISSUE THREAD

**Issue by wdqffywlw** [THU-MIG/RepViT#56]
我用的环境是wsl+ubuntu+vsconde，pytoch安装好了，repvit对应项目所需要的包也安装完毕。在vscode的terminal下，执行命令：

python  --master_port 12346  main.py --model repvit_m0_9 --data-path ~/imagenet --dist-eval ，（因为只有一个gpu，去掉了参数
 -m torch.distributed.launch --nproc_per_node=8 --master_port 12346 --use_env），运行后，出现提示:
Creating model: repvit_m0_9
Traceback (most recent call last):
  File "/home/zhifan/project/RepViT/main.py", line 485, in <module>
    main(args)
  File "/home/zhifan/project/RepViT/main.py", line 267, in main
    model = create_model(
  File "/home/zhifan/anaconda3/envs/pytorch/lib/python3.9/site-packages/timm/models/factory.py", line 71, in create_model
    model = create_fn(pretrained=pretrained, pretrained_cfg=pretrained_cfg, **kwargs)
TypeError: repvit_m0_9() got an unexpected keyword argument 'pretrained_cfg'
这个问题该如何解决？

**Comment by Kaze816** [comment]
到底是怎么解决的呀？

**Comment by Epiee** [comment]
这个错误表明 create_model(n, num_classes=1000) 调用时，repvit_m0_9 函数没有正确处理 timm 库传入的 pretrained_cfg 参数。create_model 会默认传递 pretrained_cfg 参数，因此需要在 repvit_m0_9 函数中包含该参数，即使你不使用它。
你可以通过在 repvit_m0_9 函数定义中添加 **kwargs 来解决这个问题，允许该函数接受未预期的参数。例如，在 repvit.py 文件中找到 repvit_m0_9 函数定义，并修改为：def repvit_m0_9(pretrained=False, num_classes=1000, distillation=False, **kwargs):
就可以解决问题，希望可以帮助到你
