### ISSUE TITLE
how to understand the meaning of variable 'hs' in RepViTBlock

### ISSUE THREAD

**Issue by qishuaihui** [THU-MIG/RepViT#7]
how to understand the meaning of variable 'hs' in RepViTBlock? I find it can not control the activation function.

we can  find it from the repvit.py and it is defined as follows:
nn.GELU() if use_hs else nn.GELU(),

**Comment by jameslahm** [comment]
Hi, 'hs' is indeed an unused variable. It can be removed in RepViTBlock.
